version: '3.1'
services:

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mediscreen"
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8083:8083"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8084:8084"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  notes:
    build: ./mediscreen-notes/
    image: juanlfr/mediscreen_p9_oc/mediscreen-notes
    container_name: notes
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/Notes
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - mongo-express

  risk:
    build: ./mediscreen-risk/
    image: juanlfr/mediscreen_p9_oc/mediscreen-risk
    container_name: risk
    ports:
      - "8082:8082"

  register:
    build: ./mediscreen-register/
    image: juanlfr/mediscreen_p9_oc/mediscreen-register
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/mediscreen?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=user
      - spring.datasource.password=user
    container_name: register
    ports:
      - "8080:8080"
    depends_on:
      - notes
      - risk
      - mysql